---
title: "Bachelor Degree Holders in Dallas, Texas (and some random median age graph I found)"
---


```{r}
#| echo: false
#| message: false
#| warning: false
library(tidyverse)
library(tidycensus)
library(leaflet)

dallas_bachelors <- read_rds("data/dallas.rds")

pal <- colorNumeric(
  palette = "magma",
  domain = dallas_bachelors$estimate
)

leaflet() %>%
  addProviderTiles(providers$Stamen.TonerLite) %>%
  addPolygons(data = dallas_bachelors,
              color = ~pal(estimate),
              weight = 0.5,
              smoothFactor = 0.2,
              fillOpacity = 0.5,
              label = ~estimate) %>%
  addLegend(position = "bottomright",
            pal = pal,
            values = dallas_bachelors$estimate,
            title = "% with bachelor's<br/>degree")
```


```{r}
#| echo: false
#| message: false
#| warning: false

library(tidyverse)
library(tidycensus)
library(tigris)
us_median_age <- read_rds("data/median_age.rds")
ggplot(data = us_median_age, aes(fill = estimate)) + 
  geom_sf() + 
  scale_fill_distiller(palette = "RdPu", 
                       direction = 1) + 
  labs(title = "  Median Age by State, 2019",
       caption = "Data source: 2019 1-year ACS, US Census Bureau",
       fill = "ACS estimate") + 
  theme_void()

```

